import { Cords } from './Cords';
// Generated by https://quicktype.io

export interface Slope {
  id: number;
  name: string;
  city: string;
  slope: number;
  cords: Cords;
  photo: string;
  favorite: boolean;
}
